export const GET_DATA_USER = 'GET_DATA_USER';
export const GET_DATA_USER_SUCCESS = 'GET_DATA_USER_SUCCESS';
export const GET_DATA_USER_FAILURE = 'GET_DATA_USER_FAILURE';
export const ADD_MY_FAVORITE = 'ADD_MY_FAVORITE';
